# Generated by Django 2.2.5 on 2021-01-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='saved_address',
        ),
    ]
