# Generated by Django 2.2.5 on 2021-01-03 05:50

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0003_auto_20210103_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ref_id', models.CharField(default=orders.models.Orders.generate_id, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Delivery'), (1, 'Pick-up')])),
                ('status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Fetch'), (2, 'Received'), (3, 'Confirmed'), (4, 'Processing'), (5, 'Ready'), (6, 'Given')])),
                ('service', models.IntegerField(choices=[(0, 'Wash and Dry'), (1, 'Wash, Dry, and Fold'), (2, 'Dry Cleaning')])),
                ('address', models.CharField(blank=True, max_length=100)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('pickup_time', models.DateField(blank=True, null=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_user.Customer')),
            ],
        ),
    ]
