# Generated by Django 2.2.5 on 2020-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ref_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=50)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('pickup_time', models.DateTimeField()),
            ],
        ),
    ]
