# Generated by Django 2.2.5 on 2020-11-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
